name: Edit and Push d.sh

on:
  push:
    branches:
      - main

jobs:
  edit-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run d.sh script to edit the file
        run: bash d.sh

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add d.sh
          git commit -m "Update d.sh via GitHub Actions"
          git push
