name: Test Timeout Workflow

on:
  push:
    branches:
      - main

jobs:
  test-job:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Simulate delay
        run: sleep 300  # This will sleep for 5 minutes, exceeding the 1-minute timeout
