name: Edit d.sh and Push Changes

on:
  push:
    branches:
      - main

jobs:
  edit-dsh-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Edit the d.sh file
        run: |
          echo 'echo "Hello, World!"' > d.sh

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add d.sh
          git commit -m "Edit d.sh via GitHub Actions"
          git push
