name: Edit and Push d.sh

on:
  push:
    branches:
      - main

jobs:
  edit-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Grant execute permissions to d.sh
        run: chmod +x d.sh

      - name: Edit the d.sh file
        run: |
          echo 'echo "Hello, World!"' > d.sh

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Commit and push changes
        run: |
          gh auth login --with-token ${{ secrets.GH_TOKEN }}
          git add d.sh
          git commit -m "Edit d.sh via GitHub Actions"
          git push origin HEAD:main
