name: Edit File Workflow

on:
  push:
    branches:
      - main

jobs:
  edit-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Edit File
      run: echo "Your new content" > d.sh

    - name: Commit Changes
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add d.sh
        git commit -m "Update d.sh via workflow"

    - name: Push Changes
      run: |
        git push origin main
