name: Download File Workflow

on:
  push:
    branches:
      - main

jobs:
  download-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get Raw Content URL
      id: raw_url
      run: echo "::set-output name=url::$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/contents/cd10.sh" | jq -r '.download_url')"

    - name: Download File
      run: wget -O cd10.sh "${{ steps.raw_url.outputs.url }}"
